### PR TITLE
Group Dependabot PRs

### PR DESCRIPTION
**Pull request by alexberndt**

### CODE REVIEW

**Comment by AndreaGiardini** [comment]
Mmmmm grouping all of them seems a bit drastic no? What's the idea behind this?

**Comment by alexberndt** [comment]
Fair point. The idea is to reduce the number of PRs opened. 

How do we test dependabot PRs before we merge them? Do we test this for each open PR? If so, then I agree that this PR is unnecessary. If we don't test it, then we can probably just merge updates and then address issues as they occur.

**Comment by chanange** [comment]
> Fair point. The idea is to reduce the number of PRs opened.
> 
> How do we test dependabot PRs before we merge them? Do we test this for each open PR? If so, then I agree that this PR is unnecessary. If we don't test it, then we can probably just merge updates and then address issues as they occur.

If I was to action then it would depend on whether it's a major version bump or not. For major version bumps I would check/address breaking changes and action independently. For minor/patch changes I'd be more comfortable with batching.

**Comment by alexberndt** [comment]
Good input, thanks both! I don't have a strong preference, so I'll go with @AndreaGiardini's recommendation and close the PR.

We can always re-consider if we have too many PRs down the line.

**Pull request closed without merging**
