### PR TITLE
Speed up GDAL shared workflow

### PR DESCRIPTION
**Pull request by alexberndt**
Speed up CI by pinning `poetry self add keyrings-google-artifactregistry-auth==1.1.2`

* With `poetry self add keyrings-google-artifactregistry-auth`: 11-15 min 
* With `poetry self add keyrings-google-artifactregistry-auth==1.1.2`: 1 min

### CODE REVIEW

**Comment by alexberndt** [comment]
Run with 1.1.2 pin: https://github.com/20treeAI/maestro/actions/runs/7715243258/job/21029326389
Run without pin: https://github.com/20treeAI/maestro/actions/runs/7714908707/job/21028246260

You may be right about the caching though - I'm now less convinced that this is the solution 🤔

**Comment by alexberndt** [comment]
@roelofvandijkO , you may be right, because this run is now taking > 10 minutes: https://github.com/20treeAI/maestro/actions/runs/7715352224/job/21029710353?pr=24, despite using the 1.1.2 pin

**Comment by roelofvandijkO** [comment]
I doubt this influences the speed.

The big thing is cache got or miss, and all dependabot MRs by definition miss the cache.

**Comment by roelofvandijkO** [comment]
Nevertheless, I support the pin, to avoid future incompatibility with the pinned poetry version.

Could you add it everywhere in this repo?

The library ci workflow should have the command twice.

Another (maybe more robust) path would be to just add this package to all the pyproject.tom files...

**Pull request closed without merging**
