### PR TITLE
perf: use google actions cache for docker layers

### PR DESCRIPTION
**Pull request by roelofvandijkO**
Add docker layer caching: 
https://depot.dev/blog/docker-layer-caching-in-github-actions

### CODE REVIEW

**Review by juanrg — APPROVED** [review]
Thanks! This looks good to me.

**Comment by roelofvandijkO** [comment]
@juanrg I've been trying to test this somehow. Any idea how?

**Comment by juanrg** [comment]
We should benchmark it now in one of your jobs. Because this is github actions there is no way that I'm aware of to test outside of the Cloud.

**Comment by roelofvandijkO** [comment]
I tried it like this: https://github.com/20treeAI/s2p_pipelines/pull/238

Benchmarking here now: https://github.com/20treeAI/s2p_pipelines/actions/runs/6889114666/job/18742899145

**Comment by roelofvandijkO** [comment]
Test successful.

**Pull request merged**
